---
driver:
  name: azurerm
  subscription_id: '5c691912-139b-48d7-ba4f-ab30c62f11a0'
  location: 'West Europe'
  machine_size: 'Standard_D2_v3'

provisioner:
  name: chef_zero

platforms:
  - name: windows2016
    driver:
      image_urn: MicrosoftWindowsServer:WindowsServer:2016-Datacenter-smalldisk:latest

suites:
  - name: default
    run_list:
      - recipe[rabbitmq-win]
